### ISSUE TITLE
Application Insights JavaScript Updated

### ISSUE THREAD

**Issue by RehanSaeed** [JakubOleksy-Microsoft/AppInsights-WordPress#1]
Hi,

Application Insights is not logging correctly when using your plugin. I raised a bug with Microsoft. They have updated their JavaScript. You can now updated it:

https://social.msdn.microsoft.com/Forums/vstudio/en-US/89702de9-f76d-4906-a9a5-776affcbb665/how-can-unique-users-show-more-than-sessions-in-application-insights?forum=ApplicationInsights

**Comment by JakubOleksy** [comment]
The plugin doesn't include the JavaScript SDK, only the prefix, which loads the SDK. The release last week included only the SDK. Can you elaborate on the issue you are seeing with the plugin? Make sure to clear your cache, otherwise the SDK might be cached.

**Comment by RehanSaeed** [comment]
Microsoft released new AI .js files. If your plugin does not include these files then great, you don't need to do anything.

The bug was that AI was not logging sessions vs unique users correctly due to a bug in the .js.

**Comment by JakubOleksy** [comment]
Cool, just making sure.
