### ISSUE TITLE
Still being developed? Abandoned? Still working (in WP 4.8.x)?

### ISSUE THREAD

**Issue by inspiredearth** [JakubOleksy-Microsoft/AppInsights-WordPress#11]
Hi folks,
I get the impression this plug-in has been abandoned. Is that correct?
Does it still work in newer versions of Wordpress? Like 4.8.x ?

Thanks...

Jonathan

**Comment by SergeyKanzhelev** [comment]
it works. Just tested. Will update it on wordpress soon
