### ISSUE TITLE
Regex not working on a client instrumentation Page name

### ISSUE THREAD

**Issue by cedrox** [JakubOleksy-Microsoft/AppInsights-WordPress#12]
Hello
Plugin bug on tracking title on certain page :

![image](https://user-images.githubusercontent.com/10764310/36912585-69bb3a56-1e47-11e8-8e22-f367db50b8f0.png)

I don't know if this is this statement 

or more complexe regex trouble but it raise on error like that :
Uncaught SyntaxError: missing ) after argument list

Page name pattern on \wp-content\plugins\application-insights\src\Client_Instrumentation.php
  $patterns[1] = '/PAGE_NAME/';
        if (is_home() == false)
        {
            $replacements[1] = get_the_title();
        }
        else 
        {
            $replacements[1] = 'Home';
        }

**Comment by SergeyKanzhelev** [comment]
closed via #14. I'll release it on wordpress soon
