### ISSUE TITLE
Is this plugin now actively maintained?

### ISSUE THREAD

**Issue by duncanmak** [JakubOleksy-Microsoft/AppInsights-WordPress#19]
Hello @SergeyKanzhelev, I saw that you've started making commits to this repo in May. Before that, the commits stopped for about 2 years (2016 and 2017).

Is this repo being maintained now? 

Thanks!

**Comment by SergeyKanzhelev** [comment]
@duncanmak I dusted it off and ready to accept contributions. There are few people using it as far as I know.

There is a chance this repository (or at least functionality) will be moved to [Open Census](https://github.com/census-instrumentation/). This will be announced in this repo

**Comment by SergeyKanzhelev** [comment]
Closing for now - let me know if you need more info

**Comment by duncanmak** [comment]
Thanks @SergeyKanzhelev!
