### ISSUE TITLE
Error to active plugin on WordPress 4.2.2

### ISSUE THREAD

**Issue by ups216** [JakubOleksy-Microsoft/AppInsights-WordPress#2]
I'm trying to use this plugin on my WordPress MU installation of 4.2.2, the following error occured when I activate the plugin 

Plugin could not be activated because it triggered a fatal error.
Warning: require_once(vendor/autoload.php): failed to open stream: No such file or directory in D:\home\site\wwwroot\wp-content\plugins\application-insights\ApplicationInsightsPlugin.php on line 10 Fatal error: require_once(): Failed opening required 'vendor/autoload.php' (include_path='.;C:\php\pear') in D:\home\site\wwwroot\wp-content\plugins\application-insights\ApplicationInsightsPlugin.php on line 10

**Comment by JakubOleksy** [comment]
Has it worked previously for you with this setup? I am running on my 4.2.2 site and am not seeing the issue.

**Comment by ups216** [comment]
It's working now. I'm running this on Azure China website and I had to install composer on the website as a extension to make this work. I was running this on Azure Hongkong website and I didn't  have to install anything. 
Yes, I was working for me on Azure HK for WordPress 4.1.2.

**Comment by JakubOleksy** [comment]
If you are using the actual WordPress plugin installer, you shouldn't need composer since the dependencies are already pulled down into the plugin. Can you confirm you ran the installer or did you manually try to take the Github repo and deploy it?

**Comment by ups216** [comment]
I was using the WordPress plugin, but downloaded from WordPress.org and imported manually. The composer folders were there when I imported, but WordPress still complained about the error. So I had to go to Azure portal kudu console to install the composer extension to make this work. It is very strange.

**Comment by JakubOleksy** [comment]
Yes, that is very strange. If you have any ideas, let me know =)
