### ISSUE TITLE
Not working as per instructions in readme.txt

### ISSUE THREAD

**Issue by yooakim** [JakubOleksy-Microsoft/AppInsights-WordPress#3]
I've just tried to upload the code to an existing Wordpress site. I see the plugin in the WordPress admin plugin page but when I try to activate the plugin I get this:

```
Warning: require_once(vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/wp-content/plugins/ApplicationInsights/ApplicationInsightsPlugin.php on line 10

Fatal error: require_once(): Failed opening required 'vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/wp-content/plugins/ApplicationInsights/ApplicationInsightsPlugin.php on line 10
```

Where is the `/vendor/` stuff supposed to come from?

This is a Wordpress site running in a Ubuntu VM in Azure. 
/Joakim

**Comment by SyntaxC4** [comment]
Did you run [Composer](http://getcomposer.org)?

**Comment by yooakim** [comment]
No, I didn't run composer. It is hard to do on a WordPress server where you don't have full access. I assume dthis was a working Wordpress plug-in. But apparently not?
