### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by DeV1L** [JakubOleksy-Microsoft/AppInsights-WordPress#8]
Hello!

When i enable this plugin, memory consumption grow up very high on the servers (classic LAMP).

This is when plugin disabled.
```
[L root@centos-web02 ~]$ free -h
              total        used        free      shared  buff/cache   available
Mem:           7.7G        1.0G        4.3G        352M        2.4G        6.0G
Swap:          2.0G        326M        1.7G
```

And this when enabled.
```
[L root@centos-web02 ~]$ ps aux | gfree -h
              total        used        free      shared  buff/cache   available
Mem:           7.7G        2.7G        2.7G        198M        2.3G        4.5G
Swap:          2.0G        520M        1.5G
```

**Comment by DeV1L** [comment]
Look at the screenshot http://prnt.sc/dp7wwp
leaks makes this plugin unusable.

**Comment by SergeyKanzhelev** [comment]
@DeV1L I'm closing this issue as it is quite old. I reviewed code and plugin doesn't do anything beside the creation of a few objects and posting them to Application Insights endpoint. 

If you still around and can share more info on your test - I'd appreciate it. Like number of concurrent connection and load on the application.
