### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: Argument exceptionHandler

### ISSUE THREAD

**Issue by felpasl** [JakubOleksy-Microsoft/AppInsights-WordPress#9]
On PHP 7 

PHP Fatal error:  Uncaught TypeError: Argument 1 passed to ApplicationInsights\WordPress\Server_Instrumentation::exceptionHandler() must be an instance of Exception, instance of Error given in D:\home\site\wwwroot\wp-content\plugins\application-insights\src\Server_Instrumentation.php:56
Stack trace:
#0 [internal function]: ApplicationInsights\WordPress\Server_Instrumentation->exceptionHandler(Object(Error))

The Server_Instrumentation is not compatible with php7
http://php.net/set_exception_handler

**Comment by kevinlisota** [comment]
+1 for this request

**Comment by SergeyKanzhelev** [comment]
this is closed via PHP SDK version update.
